fix: standart output service
GoodRequest/AppDebugMode-iOS pull request #20
Opened 2024-02-16 14:53 UTC by marekVrican

2024-02-16 15:46 UTC, marekVrican commented
@andrej-jasso jj ako hovoris, @plajdo to daval ako private a preto mi neslo buildnut sample, nepozeral som vsak ze to bolo len nedavno menene na private tak neviem ze co s tym teda

2024-02-16 16:12 UTC, andrej-jasso commented
> @andrej-jasso jj ako hovoris, @plajdo to daval ako private a preto mi neslo buildnut sample, nepozeral som vsak ze to bolo len nedavno menene na private tak neviem ze co s tym teda

Cielom toho aby to bolo internal je ze @plajdo  to pusta uz automaticky v setup funkcii tak to nemusis volat zvonku :) 
Ten sample projekt je ale treba fixnut ajtak

2024-02-17 11:17 UTC, plajdo commented
@marekVrican @andrej-jasso ano, dal som to ako internal, kedze sa ta funkcionalita dokaze inicializovat aj sama (a celkom spolahlivo).

Premennu, co znaci, ci je povolene redirectovanie, najdes v `AppDebugModeProvider.shared`. Ak potrebujes checknut, ci je pripojeny debugger, `DebuggerService` je namiesto toho public. Cize funkcionalita sa nestratila, len mensi refactor.

Preco tu je 101 zmenenych suborov a tolko vela commitov? Nieco je asi zle vytvorene 👀.

Samotna libka by mala ist zbuildovat, mam to integrovane na BENU uz s tymto. Sample projekt opravim, to priznavam ze som zabudol :-)

2024-02-17 11:20 UTC, plajdo requested changes
pozri koment vyssie

2024-02-17 14:36 UTC, andrej-jasso commented
> @marekVrican @andrej-jasso ano, dal som to ako internal, kedze sa ta funkcionalita dokaze inicializovat aj sama (a celkom spolahlivo).
> 
> Premennu, co znaci, ci je povolene redirectovanie, najdes v `AppDebugModeProvider.shared`. Ak potrebujes checknut, ci je pripojeny debugger, `DebuggerService` je namiesto toho public. Cize funkcionalita sa nestratila, len mensi refactor.
> 
> Preco tu je 101 zmenenych suborov a tolko vela commitov? Nieco je asi zle vytvorene 👀.
> 
> Samotna libka by mala ist zbuildovat, mam to integrovane na BENU uz s tymto. Sample projekt opravim, to priznavam ze som zabudol :-)

101 suborov je tu preto lebo som force pushol celu historiu. Mazal som citlive udaje. Kedze je to public repo.
@marekVrican  prosimta rebaseni sa na main este raz

Treba nechat internal tu triedu
Sample je dobre ze si fixnul :) 
Treba zmazat screenshoty ak su tam nejake

2024-02-19 08:54 UTC, closed without merging