feat: response log detail
GoodRequest/AppDebugMode-iOS pull request #27
Opened 2024-03-04 13:04 UTC by sebastianmraz

2024-03-05 07:14 UTC, matusklasovity commented
@andrej-jasso @sebastianmraz tento a [tento](https://github.com/GoodRequest/AppDebugMode-iOS/pull/27) PR su si akosi velmi podobne 😄

2024-03-05 07:16 UTC, matusklasovity requested changes

2024-03-05 07:16 UTC, matusklasovity commented on Sources/AppDebugMode/Screens/ConsoleLogsVIew/ConsoleLogsView.swift
> +                            .ignoresSafeArea()
```suggestion
                    Color.black.opacity(0.9)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .ignoresSafeArea()

                    ProgressView()
                        .progressViewStyle(CircularProgressViewStyle(tint: AppDebugColors.primary))
                        .frame(maxWidth: 20, maxHeight: 20, alignment: .center)
```

2024-03-05 07:16 UTC, matusklasovity commented
Pokial kliknem na fetch large tak sa spinner donekonecna toci
<img width="407" alt="Snímka obrazovky 2024-03-05 o 8 16 24" src="https://github.com/GoodRequest/AppDebugMode-iOS/assets/114930016/19a66969-1b70-43b0-b910-ddbc717fdecb">

2024-03-05 07:17 UTC, matusklasovity commented
Ked uz si sa hral s navigaciou mohol by si sa pohrat aj s navigation barom. Nechsu tie buttony troska viac citatelne ako teraz.
<img width="405" alt="Snímka obrazovky 2024-03-05 o 8 17 20" src="https://github.com/GoodRequest/AppDebugMode-iOS/assets/114930016/f09c67a8-70fb-4f1f-9236-60ccac3d12dd">

2024-03-05 07:18 UTC, matusklasovity commented
<img width="402" alt="Snímka obrazovky 2024-03-05 o 8 18 15" src="https://github.com/GoodRequest/AppDebugMode-iOS/assets/114930016/1b85af8a-c9bf-4df0-b6e6-545178ae6b9a">

2024-03-14 10:02 UTC, matusklasovity approved these changes

2024-03-14 10:26 UTC, andrej-jasso approved these changes

2024-03-14 10:26 UTC, merged